### ISSUE TITLE
Lizenzen festlegen

### ISSUE THREAD

**Issue by MartinGauk** [questionpy-org/questionpy-common#17]
Wir müssen die Lizenzen festlegen für unsere einzelnen Repositories. Wir hatten ja im Prinzip schon lange darüber gesprochen, dass das Moodle-Plugin GPL werden soll und die Python-Projekte MIT.

- Unter welcher Lizenz sollte dann questionpy-docs stehen?
- Wir müssen unsere Python-Abhängigkeiten überprüfen, ob deren Lizenzen mit MIT kompatibel sind.
- Schreiben wir bei den Python-Projekten am Anfang jeder Datei einen (kurzen) Lizenztext? Dort könnte dann auch ein Verweis auf questionpy.org angebracht werden.

(Ich erstelle dieses Issue stellvertretend unter questionpy-common, auch wenn es alle Repos betrifft.)

**Comment by MHajoha** [comment]
Ich habe mithilfe von [pip-licenses](https://pypi.org/project/pip-licenses/) mal alle main-Dependencies von questionpy-sdk geprüft. Da questionpy-common eine Dependency von questionpy-server von questionpy-sdk ist, sind darun auch alle Dependencies der anderen beiden Projekte enthalten:

| Name               | Version | License                              |
|--------------------|---------|--------------------------------------|
| Faker              | 18.10.1 | MIT License                          |
| Jinja2             | 3.1.2   | BSD License                          |
| MarkupSafe         | 2.1.3   | BSD License                          |
| PyYAML             | 6.0     | MIT License                          |
| aiohttp            | 3.8.4   | Apache Software License              |
| aiohttp-jinja2     | 1.5.1   | Apache Software License              |
| aiosignal          | 1.3.1   | Apache Software License              |
| async-timeout      | 4.0.2   | Apache Software License              |
| attrs              | 23.1.0  | MIT License                          |
| charset-normalizer | 3.1.0   | MIT License                          |
| click              | 8.1.3   | BSD License                          |
| frozenlist         | 1.3.3   | Apache Software License              |
| idna               | 3.4     | BSD License                          |
| multidict          | 6.0.4   | Apache Software License              |
| psutil             | 5.9.5   | BSD License                          |
| pydantic           | 1.10.9  | MIT License                          |
| pydantic-factories | 1.17.3  | MIT License                          |
| python-dateutil    | 2.8.2   | Apache Software License; BSD License |
| questionpy-common  | 0.2.0   | UNKNOWN                              |
| questionpy-server  | 0.1.1   | UNKNOWN                              |
| semver             | 3.0.1   | BSD License                          |
| six                | 1.16.0  | MIT License                          |
| typing_extensions  | 4.6.3   | Python Software Foundation License   |
| watchdog           | 3.0.0   | Apache Software License              |
| yarl               | 1.9.2   | Apache Software License              |

Wenn ich Dinge richtig verstehe, erlauben alle davon die Wiederverbreitung unter MIT.
